### ISSUE TITLE
Cannot compile in code blocks (VM). No make file. No EXE file. 

### ISSUE THREAD

**Issue by wjvanpatten** [klahmers/Lahmers_CSCI2270_FinalProject#6]
I know these are simple issues, but I'm a novice programmer and cannot easily solve these issues. 

I've looked around on how to solve it but haven't had any success.

**Comment by klahmers** [comment]
You should be able to run the program with just the WorkoutLog.cpp, FinalProject.h, and FinalProject.cpp files.

**Comment by wjvanpatten** [comment]
I've tried to run the program through a variety of methods. I've attached a short .txt file with information on ways I've attempted to open the file. 

Maybe some of the other reviewers could offer some insight here?

[Lahmers Errors.txt](https://github.com/klahmers/Lahmers_CSCI2270_FinalProject/files/244247/Lahmers.Errors.txt)

**Comment by klahmers** [comment]
I'm not exactly sure but it might be the connection between the files.

**Comment by laurenraddatz** [comment]
I built a project and a class within it, just like we have done for our assignments, and then I copy and pasted the relevant files into main.cpp, FinalProject.cpp, and FinalProject.h. I had no problems when I ran it this way.
